Fix test

diff --git a/src/run b/src/run
--- a/src/run
+++ b/src/run
@@ -4,12 +4,21 @@
 # shellcheck source=sh_utils/log
 . "$MONOM_LIB_ROOT/sh_utils/log"
 
+if [ ! -x "$MONOM_CONFIG_FILE" ]; then
+    log::error "Error:" "Command file \"$MONOM_CONFIG_FILE\" does not have execute permissions"
+    exit 1
+fi
+
+
 echo -e "${GREEN}Using monom from: ${BLUE}$MONOM_PROJECT_ROOT${NC}"
 # shellcheck disable=SC2206
 command_chain="$*"
 
-# relative_run_path=$(echo "$@" | $MONOM_CONFIG_FILE run)
-relative_run_path=$(echo "$@" | "$MONOM_CONFIG_FILE" run)
+if [ -z "$*" ]; then
+    # todo add echo available commands
+    exit 0
+fi
+
 run_path="$MONOM_PROJECT_ROOT/$relative_run_path"
 
 # all_args=($@)
